#!/bin/bash

# This is simple maker for Shabnigroth project


# Colors
COLOR_DEFAULT="\033[0m"
COLOR_RED="\033[0;31m"
COLOR_GREEN="\033[0;32m"



# Shab folder
Shab="./.shab"



# Error file
Error=$Shab/err



# Execute
Execute="true"



# Cache path define
CachePath="$Shab/cache"



# Object file path define
ObjPath="$Shab/obj"



# Compiler
CPP="g++ -c SOURCE_FILE -o $ObjPath/OBJECT_FILE"



function error {
    touch $Error
}



function info {
    if [ $2 = "CHANGE" ]
    then
        echo -e "File $COLOR_RED$1$COLOR_DEFAULT is changed"
    fi
    if [ $2 = "NO_CHANGE" ]
    then
        echo -e "File $COLOR_GREEN$1$COLOR_DEFAULT is not changed"
    fi
}


function checkControlSumm {
    if [ -f $1 ]
    then
        FileName=`basename $1`
        CacheFile=$CachePath/$FileName

        CurrentCache=`md5sum $1 | awk '{ print $1 }'`

        # get last cache
        if [ -f $CacheFile ]
        then
            LastCache=`cat $CacheFile`
        else
            LastCache="NO_CACHE"
        fi

        if [ "$LastCache" != "$CurrentCache" ]
        then
            echo "CHANGE"
        else
            echo "NO_CHANGE"
        fi
    else
        echo "NO_CHANGE"
    fi
}



function storeControlSumm {
    # Get cache file name
    FileName=`basename $1`
    CacheFile=$CachePath/$FileName

    # GetCurrent cache
    CurrentCache=`md5sum $1 | awk '{ print $1 }'`

    echo $CurrentCache > $CacheFile
}



# Compile one cpp file
function compile_file {
    FileNameSource=$1
    FileNameHeader=${FileNameSource/.cpp/.h}
    RebuildSource=$( checkControlSumm $FileNameSource )
    RebuildHeader=$( checkControlSumm $FileNameHeader )

    info $FileNameSource $RebuildSource
    info $FileNameHeader $RebuildHeader

    if [[ $RebuildSource = "CHANGE" || $RebuildHeader = "CHANGE" ]]
    then
        FileName=`basename $1`
        Exec=${CPP/SOURCE_FILE/$1}
        ObjFile=${FileName/.cpp/.o}
        Exec=${Exec/OBJECT_FILE/$ObjFile}
        echo -e "Run compiler:"$COLOR_GREEN $Exec $COLOR_DEFAULT
        $Exec
        if [ $? -eq 0 ]
        then
            storeControlSumm $FileNameSource
            storeControlSumm $FileNameHeader
            echo -e $COLOR_GREEN"ok"$COLOR_DEFAULT
        else
            error
        fi
    fi
}



# Compile path
function build {
    List=`ls $1`
    for File in $List
    do
        [ ! -f "$Error" ] && compile_file $File
    done
}



# Header output
function header {
    echo -e $COLOR_GREEN
    echo =================================================================
    echo $1
    echo =================================================================
    echo -e $COLOR_DEFAULT
}



# Begin build
function begin {
    if [ -f $Error ]
    then
        rm $Error
    fi
}



# Remove bash folder
function begin {
    rm -rf $Shab
}




# Main

# Create cache path for md5
if [ ! -d $CachePath ]
then
    mkdir $CachePath
fi

# Create obj path
if [ ! -d $ObjPath ]
then
    mkdir $ObjPath
fi

# Create shab path
if [ ! -d $Shab ]
then
    mkdir $Shab
fi

case $1 in
    "clear")
        clear
    ;;
    "begin")
        begin
    ;;
    "header")
        [ ! -f "$Error" ] && header "$2"
    ;;
    "build")
        build "$2"
    ;;
    "execute")
        [ ! -f "$Error" ] && $2
    ;;
    *)
        echo -e "Unknown command$COLOR_RED $1$COLOR_DEFAULT at first parameter"
        echo -e "You can use:"
        echo -e "  $COLOR_GREEN header$COLOR_DEFAULT for header output. example: shab header Hello"
        echo -e "  $COLOR_GREEN build$COLOR_DEFAULT for cpp files. example: shab build hello.cpp"
        echo -e "  $COLOR_GREEN execute$COLOR_DEFAULT execute bash command. example: shab execute ls"
        echo -e "  $COLOR_GREEN clear$COLOR_DEFAULT remove shab folder. example: shab clear"
    ;;
esac
